### ISSUE TITLE
Fails when trying to convert skript-yaml datas

### ISSUE THREAD

**Issue by rudde0** [cooffeeRequired/skJson#92]
Hey there,

I want to mention about `(json from yaml file "plugins/Skript/playersaves/data.yml")` fails when reading data.yml, if data.yml contains some skript-yaml special cases.

data.yml works fine with more datas such as:
```
island:
    disband-count: 4

locals: {}

held:
    ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: VILLAGER_SPAWN_EGG
```
but it returns null (com.google.gson.JsonNull) when we add one skript-yaml datas:
```
island:
    disband-count: 4

locals: {}

held:
    ==: org.bukkit.inventory.ItemStack
    v: 3700
    type: VILLAGER_SPAWN_EGG

lastDeath: !skriptdate '2024-04-30T15:28:52.182+03:00' # <- this is the skript-yaml exclusive data
```

This is not actual bug, it's about compability actually. In my opinion, if it's not supportable, just skipping the regarding values would be fine. All operation shouldn't be null just because of some values.
